name: Daily Trigger

on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main branch
        run: action/checkout@v3
      - name: Show Directory Files
        run: ls
      - name: Run Python Command
        run: python3 hello.py
